name: Check build
on:
  push:
permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  provenance:
    needs: build
    permissions:
      actions: read
      id-token: write
      contents: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@d995948e8d53cc639c0d3ef69db31dbc243519c4 # v1.1.1
    with:
      base64-subjects: ${{ needs.build.outputs.tarball-sha256 }}
